### ISSUE TITLE
Upload binaries?

### ISSUE THREAD

**Issue by techtonik** [Foxboron/iii#6]
Would be nice to avoid rebuilding it from scratch. And build instruction would also be handy.

**Comment by Foxboron** [comment]
`go build` should be enough, it also takes a few seconds tops to build. I don't see any reasons to provide binary files.

**Comment by techtonik** [comment]
It should be `go get` first, no?

**Comment by Foxboron** [comment]
Sure, you can use that to fetch the code and compile it.

**Comment by techtonik** [comment]
So it is not just 'go build'. I mean it looks like a useful tool for users, except that it not for users. Because users also need to install go, create that long long GOPATH for it and even after the build (when users figure out the right command) they still have to hunt for their binaries.
